const settings = require("./settings");
const [firstName, lastName, birthday] = process.argv.slice(2);
var knex = require('knex')({
    client: 'pg',
    connection: {
        host: settings.hostname,
        user: settings.user,
        password: settings.password,
        database: settings.database
    }
});

knex('famous_people').insert({
    first_name: firstName,
    last_name: lastName,
    birthdate: birthday
}).returning ('id')
.then((id)=>{
    console.log("the new id generated by insert ",id);
}).finally(function(){
    knex.destroy();
})